# Matriz de Conteo

Obtener la matriz con la cantidad de palabras repetidas de cada libro

In [1]:
import os
from pathlib import Path
import re
#from collections import defaultdict
from collections import Counter
import numpy as np

In [2]:
def buscar_titulos(directorio):
    archivos_titulos = []
    # Iterar sobre todos los archivos en el directorio
    for archivo in directorio.glob('*.txt'):
            # Abrir el archivo y buscar la palabra
            titulo=archivo.stem
            archivos_titulos.append(str(titulo))
    return archivos_titulos

In [3]:
def diccionario_libros(directorio):
    palabras_individuales = []
    for archivo in directorio.glob('*.txt'):
            with open((archivo), 'r', encoding='utf-8') as file:   
             contenido = file.read()
            # Limpiar el contenido: eliminar caracteres especiales y dividir en palabras
             palabras = re.findall(r'\b[A-Za-z0-9]+\b', contenido.lower())
             palabras_individuales.extend(palabras)      
    return palabras_individuales

In [4]:
directorio_a_buscar = Path("data")  # Ruta de la carpeta "data"
titulos_encontrados = buscar_titulos(directorio_a_buscar)


In [5]:
palabras_diccionario=diccionario_libros(directorio_a_buscar)
palabras_diccionario= set(palabras_diccionario)
palabras_ordenadas = sorted(palabras_diccionario)

In [6]:
filas=len(palabras_diccionario)
columnas=len(titulos_encontrados)
matriz = np.zeros((filas, columnas), dtype=int)
print(matriz)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:

def palabras_por_libro(directorio,libro_nombre):
    palabras_individuales1 = []
    archivo = directorio / (libro_nombre + '.txt')
    # Verificar si el archivo existe
    if archivo.exists():
        with open(archivo, 'r', encoding='utf-8') as file:
            contenido = file.read()
            # Limpiar el contenido: eliminar caracteres especiales y dividir en palabras
            palabras = re.findall(r'\b[A-Za-z0-9]+\b', contenido.lower())
            palabras_individuales1.extend(palabras) 
            palabras_individuales1 = set(palabras_individuales1)
            return palabras_individuales1

In [8]:
 for j, titulo in enumerate(titulos_encontrados):
   # contador_palabras=1
   # print(matriz[j])
    palabras_por_libro_actual= palabras_por_libro(directorio_a_buscar,titulo)
    for i, palabra in enumerate(palabras_ordenadas):
        if palabra in palabras_por_libro_actual:
            matriz[i, j] = 1
            #print(matriz[i,j])

In [9]:
print(matriz)

[[1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
def palabras_por_libro1(directorio,libro_nombre):
    palabras_individuales1 = []
    archivo = directorio / (libro_nombre + '.txt')
    # Verificar si el archivo existe
    if archivo.exists():
        with open(archivo, 'r', encoding='utf-8') as file:
            contenido = file.read()
            # Limpiar el contenido: eliminar caracteres especiales y dividir en palabras
            palabras = re.findall(r'\b[A-Za-z0-9]+\b', contenido.lower())
            palabras_individuales1.extend(palabras) 
            frecuencia=Counter(palabras_individuales1)
            return frecuencia

In [11]:
for j, titulo in enumerate(titulos_encontrados):
    contador_palabras = 0
   # print(matriz[ 0,j])
    palabras_por_libro_actual = palabras_por_libro1(directorio_a_buscar, titulo)
   # print(contador_palabras+1) 
    for i, palabra in enumerate(palabras_ordenadas):
        if matriz[i, j] == 1:
           # print(contador_palabras)
            for palabra_columna, frecuencia in palabras_por_libro_actual.items():
                if palabra == palabra_columna:  # Cambiado de palabra==palabra:columna a palabra == palabra_columna
                    matriz[i, j] = frecuencia  # Cambiado de == a =
                    #print(contador_palabras)
                    continue

     #   else:
      #      palabras_por_libro_actual = palabras_por_libro1(directorio_a_buscar, titulo)
       #     for palabra in palabras_por_libro_actual:
        #        contador_palabras += 1
         #       matriz[i, j] = contador_palabras

In [12]:
print(matriz)

[[ 7  0  1 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [23  1  1 ...  9  1  1]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [13]:
titulo='20_hrs_40_min_'
palabras_por_libro_actual = palabras_por_libro1(directorio_a_buscar, titulo)
print(palabras_por_libro_actual)

Counter({'the': 2718, 'of': 1321, 'to': 1077, 'and': 1048, 'a': 1022, 'in': 810, 'i': 662, 'is': 469, 'was': 439, 'it': 431, 'for': 360, 'with': 358, 'we': 354, 'that': 337, 'as': 290, 'on': 260, 'are': 250, 'at': 247, 'be': 224, 'had': 220, 'from': 206, 'have': 199, 'by': 197, 'or': 190, 'one': 184, 's': 177, 'not': 174, 'this': 164, 'my': 162, 'there': 159, 'which': 158, 'were': 153, 'an': 150, 'all': 149, 't': 148, 'but': 144, 'air': 137, 'he': 136, 'out': 131, 'so': 130, 'plane': 125, 'flying': 121, 'me': 121, 'they': 119, 'been': 118, 'has': 115, 'if': 113, 'you': 111, 'our': 108, 'can': 106, 'gutenberg': 97, 'when': 95, 'no': 93, 'project': 92, 'flight': 92, 'first': 91, 'any': 91, 'off': 91, 'time': 90, 'us': 87, 'up': 87, 'some': 85, 'about': 83, 'who': 82, 'just': 82, 'will': 81, 'would': 81, 'her': 80, 'work': 78, 'bill': 78, 'she': 76, 'over': 74, 'could': 73, 'his': 73, 'more': 72, 'illustration': 71, '1': 71, 'what': 70, 'their': 70, 'only': 69, 'than': 69, 'see': 69, 'oth

In [15]:
np.save("matriz_de_Conteo.npy", matriz)